### ISSUE TITLE
Sort inside Group or Sub-group

### ISSUE THREAD

**Issue by hruda12** [mminin/QGIS-misc-plugins#2]
Dear Mikhail,
I thank you for your job.  I appreciate your plugin "Sort layers" for QGIS.
I do not know if you plan to develop it further. 
However, for a GROUP I would expect to have sorted only the layers in that Group (or sub-group). 

Now, I am getting just this error:

> Traceback (most recent call last):
> 			  File "C:/Users/jurajb/.qgis2/python/plugins\SortLayers\sort_layers.py", line 68, in run
> 			    mLNED     = LayerNamesEnumDict(root.children())
> 			  File "C:/Users/jurajb/.qgis2/python/plugins\SortLayers\sort_layers.py", line 67, in <lambda>
> 			    for q in enumerate(listCh)}
> 			  File "C:/Users/jurajb/.qgis2/python/plugins\SortLayers\sort_layers.py", line 67, in <dictcomp>
> 			    for q in enumerate(listCh)}
> 			AttributeError: 'QgsLayerTreeGroup' object has no attribute 'layerName'

Regards,
Juraj

**Comment by gacarrillor** [comment]
Hi @hruda12 , see https://gis.stackexchange.com/a/397800/4972 for a solution.
